# Generated by Django 3.2.23 on 2023-11-17 00:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewform',
            name='departureTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewform',
            name='timeTaken',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
