# Generated by Django 3.2.23 on 2023-11-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0002_auto_20231117_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('continent', models.CharField(max_length=200)),
                ('days', models.CharField(max_length=200)),
            ],
        ),
    ]
