# Generated by Django 3.2.23 on 2023-11-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0003_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('mobileNo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('checkIn', models.DateTimeField()),
                ('checkOut', models.DateTimeField()),
                ('adult', models.PositiveIntegerField()),
                ('kid', models.PositiveIntegerField()),
                ('specialRequest', models.CharField(max_length=200)),
            ],
        ),
    ]
