# Generated by Django 3.2.23 on 2023-11-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0006_popular_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular',
            name='title',
            field=models.CharField(default='Loved Places', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popular',
            name='tt',
            field=models.CharField(default='Welcome all', max_length=200),
            preserve_default=False,
        ),
    ]
