# Generated by Django 3.2.23 on 2023-11-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0007_auto_20231128_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=200)),
            ],
        ),
    ]
